### ISSUE TITLE
About the evaluation metrics

### ISSUE THREAD

**Issue by Backdrop9019** [sgvaze/generalized-category-discovery#10]
Hi,
Your repo said that there are v1 and v2 as evaluation metrics, what is it exactly? Which part of the paper can I find?

**Comment by sgvaze** [comment]
Hi! Please see Appendix E for an explanation on the choice of evaluation metric. 'v1' evaluates ACC on 'Old' and 'New' subsets the same way 'Legacy NCD' does in Figure 6 in the appendix, while 'v2' is 'Ours'. 

Hope this helps!
