### ISSUE TITLE
'small_train' and 'small_validation' of herbarium19

### ISSUE THREAD

**Issue by sesmae** [sgvaze/generalized-category-discovery#14]
Hi, I was looking into the dataset for Herbarium19. After downloading the dataset , I can only see 3 splits :'train', 'validation' and 'test'. May I know what are the 'small_train' and 'small_validation' which you used in herbarium_19.py ? Also, each training epoch for herbarium19 takes a very long time to run. Is it the reason that you used a subset of it?

**Comment by sgvaze** [comment]
Hello! Many apologies for the delayed reply.

If I recall, 'small_train' and 'small_validation' simply refer to ```tar``` files which are available with the images already resized (to save disk space). They are available [here](https://www.kaggle.com/competitions/herbarium-2019-fgvc6/data). 

Regarding training times, I also recall the epochs taking a little longer than for other datasets. However, we use all the available data to create our train (labelled and unlabelled) and val (only for 'old' classes) splits.
