### ISSUE TITLE
Range-based masks are incompatiable with SSB splits

### ISSUE THREAD

**Issue by xwen99** [sgvaze/generalized-category-discovery#16]
In multiple places in the codebase, the mask to identify one class comes from the old or new classes is computed as:

- https://github.com/sgvaze/generalized-category-discovery/blob/262519540c3452c6b8276dc203b4e9067378c552/methods/clustering/k_means.py#L48-L49
- https://github.com/sgvaze/generalized-category-discovery/blob/262519540c3452c6b8276dc203b4e9067378c552/methods/contrastive_training/contrastive_training.py#L313-L314
- https://github.com/sgvaze/generalized-category-discovery/blob/262519540c3452c6b8276dc203b4e9067378c552/methods/estimate_k/estimate_k.py#L49-L50
- https://github.com/sgvaze/generalized-category-discovery/blob/262519540c3452c6b8276dc203b4e9067378c552/methods/estimate_k/estimate_k.py#L116-L117

However, this is only compatible with the setting that all old classes are consecutive (e.g., 0, 1, ..., n_old_classes - 1). For the SSB splits where the old class indexes are non-consecutive, it can result in incorrect old-new splits.

Influence of this bug: the `old/new ACCs` of CUB & Stanford Cars are not reliable (if use_ssb_splits==True), but the `all ACC` is not affected.

Possible fix: replace `range(len(args.train_classes))` with `args.train_classes`.

**Comment by eatamath** [comment]
I think the author have to re-run all the experiments on SSB split datasets, since the checkpointing strategy depends on the performance of Old Classes. @sgvaze

**Comment by sgvaze** [comment]
Hi thanks for raising this point @xwen99 

[This line](https://github.com/sgvaze/generalized-category-discovery/blob/831a645c3d09a68ec4633a45741025765bacf7e0/data/get_datasets.py#L68) ensures that the 'Old' classes are mapped to the first half of the dataset class indices (and that they are all contiguous). Hope this helps!

**Comment by xwen99** [comment]
> Hi thanks for raising this point @xwen99
> 
> [This line](https://github.com/sgvaze/generalized-category-discovery/blob/831a645c3d09a68ec4633a45741025765bacf7e0/data/get_datasets.py#L68) ensures that the 'Old' classes are mapped to the first half of the dataset class indices (and that they are all contiguous). Hope this helps!

Aha, sorry I overlooked this part, seems everything works fine then, thanks!

**Comment by eatamath** [comment]
Thank you
