### ISSUE TITLE
Can't find the file: dino_vitbase16_pretrain.pth

### ISSUE THREAD

**Issue by CYDping** [sgvaze/generalized-category-discovery#17]
Hi, thanks for sharing.

But I met a problem that is I can't the file: dino_vitbase16_pretrain.pth, from the project folder. Could you please upload this file? 

Thanks a lot.

**Comment by yuhodots** [comment]
I think you can find the DINO backbone in the original DINO repository ([here: ViT-B/16](https://github.com/facebookresearch/dino))!

**Comment by CYDping** [comment]
Thanks! I've downloaded the file from the link.
