### ISSUE TITLE
table 2,3 number clarification

### ISSUE THREAD

**Issue by cassie101** [sgvaze/generalized-category-discovery#6]
Hi, great work.

May I know if table 2 and 3 are based on clustering method mentioned in 3.1.2 or 3.2? 

The numbers in table 3, specfically on Herbarium19 shows (35.4 | 51.0 | 27.0) which is the same as table 5 (6), which suggest semi-sup k-means was used to generate the results for table 3. While, table 2 results on CIFAR100 shows (70.8 | 77.6 | 57.0 ) which is different from table 5. Thanks in advanced.

**Comment by sgvaze** [comment]
Hi, great spot. Indeed we noticed this mistake ourselves recently. We re-ran the ablations after changing the evaluation metric, so Table 5 figures are correct. We will correct this in the ArXiv version. Also, all figures in Tab 2 and Tab 3 are with SS-K-Means.

Hope this helps.
