### ISSUE TITLE
Can you provide ssb_splits?

### ISSUE THREAD

**Issue by kleinzcy** [sgvaze/generalized-category-discovery#7]
Thanks for your great work and nice code.

When I try to re-implement experiments, I found there are no ssb_splits. Can you provide ssb_splits?

**Comment by yuhodots** [comment]
Hi, 
I'm also looking at this work, and I think [here](https://github.com/sgvaze/generalized-category-discovery/tree/main/data/ssb_splits) is what you want.

**Comment by kleinzcy** [comment]
@yuhodots Thanks very much! It works.
