### ISSUE TITLE
one question in contrastive_train.py

### ISSUE THREAD

**Issue by eatamath** [sgvaze/generalized-category-discovery#8]
Dear Sagar Vaze,
I am reading your released code of your interesting paper Genearalized Cateogory Discovery. However, I seem to be confused about one implementation in the file 'contrastive_training.py'. In your function 'test_kmeans.py', when doing the KMeans, why the @n_clusters equals to the ground-truth class number here? Do you assume here you have access to the ground-truth cluster number or I mistakenly understand the whole pipeline? Kindly could you help to explain this?

Thanks for any help you can give.

**Comment by sgvaze** [comment]
Hi, we tackle the problems separately. In our recognition experiments, we assume knowledge of 'K', and we have independent experiments to estimate K. Hope this helps!

**Comment by eatamath** [comment]
@sgvaze  thank you for reply. I have another question: what's your args.resize_lower_bound for herbarium augmentation? This argument does not appear in the argparser. Thanks!

**Comment by sgvaze** [comment]
Hi, I think this is deprecated. We no longer use that augmentation option - all models are trained with 'imagenet' augmentation by default.
